# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

version: '2'

networks:
  network:

services:

  ca_macaoE:
    image: hyperledger/fabric-ca:1.5
    labels:
      service: hyperledger-fabric
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca-macaoE
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_PORT=7050
      - FABRIC_CA_SERVER_OPERATIONS_LISTENADDRESS=0.0.0.0:17050
    ports:
      - 7050:7050
      - 17050:17050
    command: sh -c 'fabric-ca-server start -b admin:adminpw -d'
    volumes:
      - ../orgs/fabric-ca/macaoE:/etc/hyperledger/fabric-ca-server
    container_name: ca_macaoE
    networks:
      - network

  ca_spv:
    image: hyperledger/fabric-ca:1.5
    labels:
      service: hyperledger-fabric
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca-spv
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_PORT=7051
      - FABRIC_CA_SERVER_OPERATIONS_LISTENADDRESS=0.0.0.0:17051
    ports:
      - "7051:7051"
      - "17051:17051"
    command: sh -c 'fabric-ca-server start -b admin:adminpw -d'
    volumes:
      - ../orgs/fabric-ca/spv:/etc/hyperledger/fabric-ca-server
    container_name: ca_spv
    networks:
      - network

  ca_orderer:
    image: hyperledger/fabric-ca:1.5
    labels:
      service: hyperledger-fabric
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca-orderer
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_PORT=7049
      - FABRIC_CA_SERVER_OPERATIONS_LISTENADDRESS=0.0.0.0:17049
    ports:
      - 7049:7049
      - 17049:17049
    command: sh -c 'fabric-ca-server start -b admin:adminpw -d'
    volumes:
      - ../orgs/fabric-ca/ordererOrg:/etc/hyperledger/fabric-ca-server
    container_name: ca_orderer
    networks:
      - network
